version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    env_file: .env
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - mysql
    #entrypoint:
#      - python3 flask db init
#      - python3 flask db migrate
#      - python3 flask db upgrade
    #  - python3.10 run.py