version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    env_file: .env
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - mysql